# Generated by Django 4.2.4 on 2024-04-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_useraccount_is_pc_isla_investigador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_buscador_admin',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_buscador_editor',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_convenios_admin',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_convenios_editor',
        ),
    ]
